
set autoindent		" auto indent
set smartindent		" smart indentation for c-like languages
syntax enable		" enable syntax highlight
set number		" line numbers
set hidden		" enable buffers to be 'hidden' see :help hidden
set laststatus=2	" always show the status line
set backspace=indent,eol,start	" always allow backspace see https://vi.stackexchange.com/a/2163
set relativenumber
filetype plugin indent on
set termguicolors
colorscheme monokai
set expandtab
"set term=xterm-256color #Not needed for nvim?
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
"set completeopt=menu,popup #Removed due to imcompatibility with NVIM
let g:ycm_add_preview_to_completeopt = 0

nnoremap <C-c> :NERDTreeToggle<CR>

let g:NERDTreeIgnore = ['.*\.class$', '.*\.o$']
set clipboard=unnamedplus

autocmd BufNewFile,BufRead Makefile setlocal noexpandtab
hi Normal guibg=NONE ctermbg=NONE
hi LineNr guibg=NONE ctermbg=NONE

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
"let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit=ULTISNIPSDIR
"

" Tell vimtex to use zathura
let g:vimtex_view_method = 'zathura'
let g:vimtex_view_general_viwer = 'zathura'
" Copy paste from :h vimtex with only build_dir changed
"
let g:vimtex_compiler_latexmk = {
        \ 'build_dir' : 'build',
        \ 'callback' : 1,
        \ 'continuous' : 1,
        \ 'executable' : 'latexmk',
        \ 'hooks' : [],
        \ 'options' : [
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \   '-shell-escape'
        \ ],
        \}
